'use client'
import { useState, useEffect } from 'react'
import { createClient } from '@supabase/supabase-js'

const sb = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
    )

    export default function AdminBannersPage() {
      const [banners, setBanners] = useState<any[]>([])
        const [form, setForm] = useState({ title:'', subtitle:'', image_url:'', link_url:'', position:'home_top', is_active:true, price_paid:0, ends_at:'' })
          const [editing, setEditing] = useState<string|null>(null)
            const [loading, setLoading] = useState(true)
              const [msg, setMsg] = useState('')

                useEffect(() => {
                    const init = async () => {
                          const { data: auth } = await sb.auth.getUser()
                                if (!auth.user) { window.location.href = '/auth/login'; return }
                                      const { data: p } = await sb.from('user_profiles').select('role').eq('id', auth.user.id).single()
                                            if (!p || !['admin','super_admin'].includes(p.role)) { window.location.href = '/'; return }
                                                  load()
                                                      }
                                                          init()
                                                            }, [])

                                                              const load = async () => {
                                                                  setLoading(true)
                                                                      const { data } = await sb.from('banners').select('*').order('created_at', { ascending: false })
                                                                          setBanners(data || [])
                                                                              setLoading(false)
                                                                                }

                                                                                  const save = async () => {
                                                                                      if (!form.title) { setMsg('제목을 입력하세요'); return }
                                                                                          const payload = { ...form, ends_at: form.ends_at || null }
                                                                                              if (editing) {
                                                                                                    await sb.from('banners').update(payload).eq('id', editing)
                                                                                                          setMsg('수정됐습니다')
                                                                                                              } else {
                                                                                                                    await sb.from('banners').insert(payload)
                                                                                                                          setMsg('배너가 추가됐습니다')
                                                                                                                              }
                                                                                                                                  setForm({ title:'', subtitle:'', image_url:'', link_url:'', position:'home_top', is_active:true, price_paid:0, ends_at:'' })
                                                                                                                                      setEditing(null)
                                                                                                                                          setTimeout(() => setMsg(''), 3000)
                                                                                                                                              load()
                                                                                                                                                }
                                                                                                                                                
                                                                                                                                                  const del = async (id: string) => {
                                                                                                                                                      if (!confirm('삭제할까요?')) return
                                                                                                                                                          await sb.from('banners').delete().eq('id', id)
                                                                                                                                                              load()
                                                                                                                                                                }
                                                                                                                                                                
                                                                                                                                                                  const toggle = async (b: any) => {
                                                                                                                                                                      await sb.from('banners').update({ is_active: !b.is_active }).eq('id', b.id)
                                                                                                                                                                          load()
                                                                                                                                                                            }
                                                                                                                                                                            
                                                                                                                                                                              const fs = 'w-full border border-slate-200 rounded-lg px-3 py-2 text-[13px] outline-none focus:border-indigo-400'
                                                                                                                                                                              
                                                                                                                                                                                return (
                                                                                                                                                                                    <div className="min-h-screen bg-slate-100 max-w-2xl mx-auto pb-10">
                                                                                                                                                                                          <div className="bg-[#1a1a2e] px-5 pt-10 pb-6 flex items-center justify-between">
                                                                                                                                                                                                  <div>
                                                                                                                                                                                                            <h1 className="text-[20px] font-extrabold text-white">배너 광고 관리</h1>
                                                                                                                                                                                                                      <p className="text-white/40 text-[12px] mt-0.5">광고비: $200~500/월 per 배너</p>
                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                      <a href="/admin" className="text-white/40 text-[13px] border border-white/20 px-3 py-1.5 rounded-lg">관리자</a>
                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                  {msg && <div className="mx-4 mt-4 bg-green-50 border border-green-200 rounded-xl px-4 py-3 text-[14px] font-bold text-green-700">{msg}</div>}
                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                        <div className="mx-4 mt-4 bg-white rounded-xl border border-slate-200 p-4 space-y-3">
                                                                                                                                                                                                                                                                <div className="text-[14px] font-bold text-slate-700">{editing ? '배너 수정' : '새 배너 등록'}</div>
                                                                                                                                                                                                                                                                        <input value={form.title} onChange={e => setForm(f => ({...f, title: e.target.value}))} placeholder="제목 *" className={fs} />
                                                                                                                                                                                                                                                                                <input value={form.subtitle} onChange={e => setForm(f => ({...f, subtitle: e.target.value}))} placeholder="부제목" className={fs} />
                                                                                                                                                                                                                                                                                        <input value={form.image_url} onChange={e => setForm(f => ({...f, image_url: e.target.value}))} placeholder="이미지 URL (선택)" className={fs} />
                                                                                                                                                                                                                                                                                                <input value={form.link_url} onChange={e => setForm(f => ({...f, link_url: e.target.value}))} placeholder="링크 URL" className={fs} />
                                                                                                                                                                                                                                                                                                        <div className="grid grid-cols-2 gap-3">
                                                                                                                                                                                                                                                                                                                  <select value={form.position} onChange={e => setForm(f => ({...f, position: e.target.value}))} className={fs + ' bg-white'}>
                                                                                                                                                                                                                                                                                                                              <option value="home_top">홈 상단</option>
                                                                                                                                                                                                                                                                                                                                          <option value="home_middle">홈 중간</option>
                                                                                                                                                                                                                                                                                                                                                      <option value="category_top">카테고리 상단</option>
                                                                                                                                                                                                                                                                                                                                                                </select>
                                                                                                                                                                                                                                                                                                                                                                          <input type="number" value={form.price_paid} onChange={e => setForm(f => ({...f, price_paid: Number(e.target.value)}))} placeholder="광고비 ($)" className={fs} />
                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                          <input type="datetime-local" value={form.ends_at} onChange={e => setForm(f => ({...f, ends_at: e.target.value}))} className={fs} />
                                                                                                                                                                                                                                                                                                                                                                                                  <div className="flex gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                            <button onClick={save} className="flex-1 bg-indigo-600 text-white rounded-lg py-2.5 text-[13px] font-bold">{editing ? '수정 저장' : '배너 추가'}</button>
                                                                                                                                                                                                                                                                                                                                                                                                                      {editing && <button onClick={() => { setForm({ title:'', subtitle:'', image_url:'', link_url:'', position:'home_top', is_active:true, price_paid:0, ends_at:'' }); setEditing(null) }} className="px-4 bg-slate-100 text-slate-600 rounded-lg text-[13px] font-bold">취소</button>}
                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="px-4 mt-4 space-y-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                  {loading ? <div className="flex justify-center py-10"><div className="w-8 h-8 border-2 border-indigo-500 border-t-transparent rounded-full animate-spin" /></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                          : banners.map(b => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div key={b.id} className={`bg-white rounded-xl border p-4 ${b.is_active ? 'border-slate-200' : 'border-slate-100 opacity-60'}`}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="flex items-start justify-between mb-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="text-[14px] font-bold">{b.title}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {b.subtitle && <div className="text-[12px] text-slate-400">{b.subtitle}</div>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <span className={`text-[10px] font-black px-2 py-1 rounded-full ${b.is_active ? 'bg-green-100 text-green-700' : 'bg-slate-100 text-slate-500'}`}>{b.is_active ? '노출중' : '숨김'}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div className="text-[11px] text-slate-400 mb-3">위치: {b.position} | 광고비: ${b.price_paid} | 클릭: {b.click_count}회</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="flex gap-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button onClick={() => { setForm({ title:b.title, subtitle:b.subtitle||'', image_url:b.image_url||'', link_url:b.link_url||'', position:b.position, is_active:b.is_active, price_paid:b.price_paid, ends_at:b.ends_at?.slice(0,16)||'' }); setEditing(b.id); window.scrollTo(0,0) }} className="text-[12px] font-bold px-3 py-1.5 rounded-lg bg-indigo-50 text-indigo-600">수정</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button onClick={() => toggle(b)} className={`text-[12px] font-bold px-3 py-1.5 rounded-lg ${b.is_active ? 'bg-slate-100 text-slate-500' : 'bg-green-50 text-green-600'}`}>{b.is_active ? '숨기기' : '보이기'}</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button onClick={() => del(b.id)} className="text-[12px] font-bold px-3 py-1.5 rounded-lg bg-red-50 text-red-500">삭제</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
